name: offline-download
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装环境
      - name: Install Enviroment
        run: |
          sudo apt-get update
          sudo apt-get install wget
          sudo apt-get install unar

      # 获取最新Release
      - name: Fetch
        run: |
          echo "开始下载"
          wget 'https://github.com/EhTagTranslation/EhSyringe/releases/latest/download/ehsyringe.chrome.zip'

      # 解压
      - name: Decompression
        run: |
          echo "开始解压："
          ls | egrep '\.(rar|zip)$'
          echo ""
          ls | egrep '\.(rar|zip)$' | xargs -d '\n' -n1 -i unar "{}"

      # 处理Manifest
      - name: Parse Manifest
        run: |
          node parse.js

      # 打包扩展
      - name: Pack ZIP
      - uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'ehsyringe.chrome'
          zipFilePath: 'build/extension.zip'
      - name: Pack CRX
      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'build/extension.zip',
          crxFilePath: 'build/extension.crx'
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }},
          updateXmlPath: 'build/update.xml',      
          updateXmlCodebaseUrl: "https://github.com/${{ github.repository }}/releases/latest/download/extension.crx"